### ISSUE TITLE
arm64 builds please

### ISSUE THREAD

**Issue by necrose99** [ventoy/PXE#84]
```
#.github/workflows/arm-build.yml
name: Build iVentoy for ARM

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-arm:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [arm64, armv7]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build iVentoy for ${{ matrix.arch }}
        run: |
          docker buildx build --platform linux/${{ matrix.arch }} -t iventoy:${{ matrix.arch }} .

      - name: Push Docker Image
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_TOKEN"
          docker push iventoy:${{ matrix.arch }}

```
```
#am64-dockerfile
# Example Dockerfile for iVentoy
FROM ubuntu:20.04

# Install necessary dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    gcc \
    make \
    curl \
    libssl-dev \
    # Add other dependencies here \
    && apt-get clean

# Copy iVentoy source code into the image
COPY . /opt/iventoy

WORKDIR /opt/iventoy

# Build the iVentoy binaries
RUN make

# Set up entrypoint for running iVentoy
ENTRYPOINT ["/opt/iventoy/iventoy.sh"]

```
